import os
import django
from datetime import datetime, timedelta
import requests
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

API_KEY = os.environ.get("CONGRESS_API_KEY")

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")
django.setup()
from server.models import CongressMember, Committee, Stock, Sector, CommitteeMembership


us_states_territories = {
    "Alabama": "AL",
    "Alaska": "AK",
    "American Samoa": "AS",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Guam": "GU",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Marshall Islands": "MH",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Northern Mariana Islands": "MP",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Palau": "PW",
    "Pennsylvania": "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virgin Islands": "VI",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}
gics_sectors = {
    "Technology": "45",
    "Telecommunications": "50",
    "Healthcare": "35",
    "Health Care": "35",
    "Financials": "40",
    "Finance": "40",
    "Real Estate": "60",
    "Consumer Discretionary": "25",
    "Consumer Staples": "30",
    "Industrials": "20",
    "Basic Materials": "15",
    "Energy": "10",
    "Utilities": "55",
    None: "00",
    "Miscellaneous": "00",
    "nan": "00",
    float("nan"): "00",
    "Information Technology": "45",
}


## Adds all members from 119 congress
def getMembers():
    url = "https://api.congress.gov/v3/member/congress/119"
    members_of_congress = []
    for i in range(0, 4):
        params = {
            "api_key": API_KEY,
            "limit": 250,
            "current_member": "true",
            "offset": 250 * i,
        }
        response = requests.get(url, params=params)
        members = response.json()["members"]
        for member in members:
            name = member["name"]
            parts = name.split(", ")
            last_name = parts[0]
            first_name = parts[1]
            middle_initial = ""

            m = {
                "bio_guide_id": member["bioguideId"],
                "party": member["partyName"][0],
                "state": us_states_territories[member["state"]],
                "chamber": member["terms"]["item"][-1]["chamber"][0],
                "first_name": first_name,
                "middle_initial": middle_initial,
                "last_name": last_name,
                "term": len(member["terms"]["item"]),
            }
            members_of_congress.append(
                CongressMember(
                    bio_guide_id=m["bio_guide_id"],
                    first_name=m["first_name"],
                    middle_initial=m["middle_initial"],
                    last_name=m["last_name"],
                    chamber=m["chamber"],
                    party=m["party"],
                    state=m["state"],
                    term=m["term"],
                )
            )
    CongressMember.objects.bulk_create(members_of_congress)
    print(f"{len(members_of_congress)} members added")



## Adds all stocks
def getStocks():
    df = pd.read_csv("./data/NASDAQ.csv")
    df["sector_code"] = df["Sector"].map(gics_sectors)
    unmatched_sectors = set()
    stocks = []
    for _, row in df.iterrows():
        sector_code = row["sector_code"]
        try:
            sector_instance = Sector.objects.get(sector_code=row["sector_code"])
        except:
            unmatched_sectors.add(row["Sector"])

        stock = Stock(sector=sector_instance, name=row["Name"], ticker=row["Symbol"])
        stocks.append(stock)
    Stock.objects.bulk_create(stocks, ignore_conflicts=True)
    print("Inserted stocks")

    print(unmatched_sectors)


## Adds all sectors
def getSectors():
    sectors = [
        Sector(
            sector_code="00", sector_name="Other", description="Other or misc. sectors"
        ),
        Sector(
            sector_code="10",
            sector_name="Energy",
            description="Companies involved in oil, gas, coal, and renewable energy.",
        ),
        Sector(
            sector_code="15",
            sector_name="Basic Materials",
            description="Companies that produce chemicals, construction materials, and metals.",
        ),
        Sector(
            sector_code="20",
            sector_name="Industrials",
            description="Businesses in manufacturing, transportation, and services.",
        ),
        Sector(
            sector_code="25",
            sector_name="Consumer Discretionary",
            description="Retail, media, entertainment, and luxury goods companies.",
        ),
        Sector(
            sector_code="30",
            sector_name="Consumer Staples",
            description="Companies providing essential consumer products such as food and beverages.",
        ),
        Sector(
            sector_code="35",
            sector_name="Healthcare",
            description="Pharmaceutical, biotechnology, and medical device companies.",
        ),
        Sector(
            sector_code="40",
            sector_name="Financials",
            description="Banks, investment firms, and insurance companies.",
        ),
        Sector(
            sector_code="45",
            sector_name="Technology",
            description="Software, hardware, and IT services companies.",
        ),
        Sector(
            sector_code="50",
            sector_name="Telecommunications",
            description="Providers of internet, phone, and wireless services.",
        ),
        Sector(
            sector_code="55",
            sector_name="Utilities",
            description="Electric, gas, and water service providers.",
        ),
        Sector(
            sector_code="60",
            sector_name="Real Estate",
            description="Real estate investment trusts (REITs) and property management companies.",
        ),
    ]
    Sector.objects.bulk_create(sectors)


senate_committees = {
    "Agriculture, Nutrition, and Forestry": [
        "Boozman, John (AR)",
        "McConnell, Mitch (KY)",
        "Hoeven, John (ND)",
        "Ernst, Joni (IA)",
        "Hyde-Smith, Cindy (MS)",
        "Marshall, Roger (KS)",
        "Tuberville, Tommy (AL)",
        "Justice, James C. (WV)",
        "Grassley, Chuck (IA)",
        "Thune, John (SD)",
        "Fischer, Deb (NE)",
        "Moran, Jerry (KS)",
        "Klobuchar, Amy (MN)",
        "Bennet, Michael F. (CO)",
        "Smith, Tina (MN)",
        "Durbin, Richard J. (IL)",
        "Booker, Cory A. (NJ)",
        "Lujan, Ben Ray (NM)",
        "Warnock, Raphael G. (GA)",
        "Welch, Peter (VT)",
        "Fetterman, John (PA)",
        "Schiff, Adam B. (CA)",
        "Slotkin, Elissa (MI)",
    ],
    "Appropriations": [
        "Collins, Susan M. (ME)",
        "McConnell, Mitch (KY)",
        "Murkowski, Lisa (AK)",
        "Graham, Lindsey (SC)",
        "Moran, Jerry (KS)",
        "Hoeven, John (ND)",
        "Boozman, John (AR)",
        "Capito, Shelley Moore (WV)",
        "Kennedy, John (LA)",
        "Hyde-Smith, Cindy (MS)",
        "Hagerty, Bill (TN)",
        "Britt, Katie Boyd (AL)",
        "Mullin, Markwayne (OK)",
        "Fischer, Deb (NE)",
        "Rounds, Mike (SD)",
        "Murray, Patty (WA)",
        "Durbin, Richard J. (IL)",
        "Reed, Jack (RI)",
        "Shaheen, Jeanne (NH)",
        "Merkley, Jeff (OR)",
        "Coons, Christopher A. (DE)",
        "Schatz, Brian (HI)",
        "Baldwin, Tammy (WI)",
        "Murphy, Christopher (CT)",
        "Van Hollen, Chris (MD)",
        "Heinrich, Martin (NM)",
        "Peters, Gary C. (MI)",
        "Gillibrand, Kirsten E. (NY)",
        "Ossoff, Jon (GA)",
    ],
    "Armed Services": [
        "Wicker, Roger F. (MS)",
        "Fischer, Deb (NE)",
        "Cotton, Tom (AR)",
        "Rounds, Mike (SD)",
        "Ernst, Joni (IA)",
        "Sullivan, Dan (AK)",
        "Cramer, Kevin (ND)",
        "Scott, Rick (FL)",
        "Tuberville, Tommy (AL)",
        "Mullin, Markwayne (OK)",
        "Budd, Ted (NC)",
        "Schmitt, Eric (MO)",
        "Banks, Jim (IN)",
        "Sheehy, Tim (MT)",
        "Reed, Jack (RI)",
        "Shaheen, Jeanne (NH)",
        "Gillibrand, Kirsten E. (NY)",
        "Blumenthal, Richard (CT)",
        "Hirono, Mazie K. (HI)",
        "Kaine, Tim (VA)",
        "King, Angus S. (ME)",
        "Warren, Elizabeth (MA)",
        "Peters, Gary C. (MI)",
        "Duckworth, Tammy (IL)",
        "Rosen, Jacky (NV)",
        "Kelly, Mark (AZ)",
        "Slotkin, Elissa (MI)",
    ],
    "Banking, Housing, and Urban Affairs": [
        "Scott, Tim (SC)",
        "Crapo, Mike (ID)",
        "Rounds, Mike (SD)",
        "Tillis, Thom (NC)",
        "Kennedy, John (LA)",
        "Hagerty, Bill (TN)",
        "Lummis, Cynthia M. (WY)",
        "Britt, Katie Boyd (AL)",
        "Ricketts, Pete (NE)",
        "Banks, Jim (IN)",
        "Cramer, Kevin (ND)",
        "Moreno, Bernie (OH)",
        "McCormick, David (PA)",
        "Warren, Elizabeth (MA)",
        "Reed, Jack (RI)",
        "Warner, Mark R. (VA)",
        "Van Hollen, Chris (MD)",
        "Cortez Masto, Catherine (NV)",
        "Smith, Tina (MN)",
        "Warnock, Raphael G. (GA)",
        "Kim, Andy (NJ)",
        "Gallego, Ruben (AZ)",
        "Blunt Rochester, Lisa (DE)",
        "Alsobrooks, Angela D. (MD)",
    ],
    "Commerce, Science, and Transportation": [
        "Cruz, Ted (TX)",
        "Thune, John (SD)",
        "Wicker, Roger F. (MS)",
        "Fischer, Deb (NE)",
        "Moran, Jerry (KS)",
        "Sullivan, Dan (AK)",
        "Blackburn, Marsha (TN)",
        "Young, Todd (IN)",
        "Budd, Ted (NC)",
        "Schmitt, Eric (MO)",
        "Curtis, John R. (UT)",
        "Moreno, Bernie (OH)",
        "Sheehy, Tim (MT)",
        "Capito, Shelley Moore (WV)",
        "Lummis, Cynthia M. (WY)",
        "Cantwell, Maria (WA)",
        "Klobuchar, Amy (MN)",
        "Schatz, Brian (HI)",
        "Markey, Edward J. (MA)",
        "Peters, Gary C. (MI)",
        "Baldwin, Tammy (WI)",
        "Duckworth, Tammy (IL)",
        "Rosen, Jacky (NV)",
        "Lujan, Ben Ray (NM)",
        "Hickenlooper, John W. (CO)",
        "Fetterman, John (PA)",
        "Kim, Andy (NJ)",
        "Blunt Rochester, Lisa (DE)",
    ],
    "Energy and Natural Resources": [
        "Lee, Mike (UT)",
        "Barrasso, John (WY)",
        "Risch, James E. (ID)",
        "Daines, Steve (MT)",
        "Cotton, Tom (AR)",
        "McCormick, David (PA)",
        "Justice, James C. (WV)",
        "Cassidy, Bill (LA)",
        "Hyde-Smith, Cindy (MS)",
        "Murkowski, Lisa (AK)",
        "Hoeven, John (ND)",
        "Heinrich, Martin (NM)",
        "Wyden, Ron (OR)",
        "Cantwell, Maria (WA)",
        "Hirono, Mazie K. (HI)",
        "King, Angus S. (ME)",
        "Cortez Masto, Catherine (NV)",
        "Hickenlooper, John W. (CO)",
        "Padilla, Alex (CA)",
        "Gallego, Ruben (AZ)",
    ],
    "Environment and Public Works": [
        "Capito, Shelley Moore (WV)",
        "Cramer, Kevin (ND)",
        "Lummis, Cynthia M. (WY)",
        "Curtis, John R. (UT)",
        "Graham, Lindsey (SC)",
        "Sullivan, Dan (AK)",
        "Ricketts, Pete (NE)",
        "Wicker, Roger F. (MS)",
        "Boozman, John (AR)",
        "Husted, Jon (OH)",
        "Whitehouse, Sheldon (RI)",
        "Sanders, Bernard (VT)",
        "Merkley, Jeff (OR)",
        "Markey, Edward J. (MA)",
        "Kelly, Mark (AZ)",
        "Padilla, Alex (CA)",
        "Schiff, Adam B. (CA)",
        "Blunt Rochester, Lisa (DE)",
        "Alsobrooks, Angela D. (MD)",
    ],
    "Finance": [
        "Crapo, Mike (ID)",
        "Grassley, Chuck (IA)",
        "Cornyn, John (TX)",
        "Thune, John (SD)",
        "Scott, Tim (SC)",
        "Cassidy, Bill (LA)",
        "Lankford, James (OK)",
        "Daines, Steve (MT)",
        "Young, Todd (IN)",
        "Barrasso, John (WY)",
        "Johnson, Ron (WI)",
        "Tillis, Thom (NC)",
        "Blackburn, Marsha (TN)",
        "Marshall, Roger (KS)",
        "Wyden, Ron (OR)",
        "Cantwell, Maria (WA)",
        "Bennet, Michael F. (CO)",
        "Warner, Mark R. (VA)",
        "Whitehouse, Sheldon (RI)",
        "Hassan, Margaret Wood (NH)",
        "Cortez Masto, Catherine (NV)",
        "Warren, Elizabeth (MA)",
        "Sanders, Bernard (VT)",
        "Smith, Tina (MN)",
        "Lujan, Ben Ray (NM)",
        "Warnock, Raphael G. (GA)",
        "Welch, Peter (VT)",
    ],
    "Foreign Relations": [
        "Risch, James E. (ID)",
        "Ricketts, Pete (NE)",
        "McCormick, David (PA)",
        "Daines, Steve (MT)",
        "Hagerty, Bill (TN)",
        "Barrasso, John (WY)",
        "Lee, Mike (UT)",
        "Paul, Rand (KY)",
        "Cruz, Ted (TX)",
        "Scott, Rick (FL)",
        "Curtis, John R. (UT)",
        "Cornyn, John (TX)",
        "Shaheen, Jeanne (NH)",
        "Coons, Christopher A. (DE)",
        "Murphy, Christopher (CT)",
        "Kaine, Tim (VA)",
        "Merkley, Jeff (OR)",
        "Booker, Cory A. (NJ)",
        "Schatz, Brian (HI)",
        "Van Hollen, Chris (MD)",
        "Duckworth, Tammy (IL)",
        "Rosen, Jacky (NV)",
    ],
    "Health, Education, Labor, and Pensions": [
        "Cassidy, Bill (LA)",
        "Paul, Rand (KY)",
        "Collins, Susan M. (ME)",
        "Murkowski, Lisa (AK)",
        "Mullin, Markwayne (OK)",
        "Marshall, Roger (KS)",
        "Scott, Tim (SC)",
        "Hawley, Josh (MO)",
        "Tuberville, Tommy (AL)",
        "Banks, Jim (IN)",
        "Husted, Jon (OH)",
        "Moody, Ashley (FL)",
        "Sanders, Bernard (VT)",
        "Murray, Patty (WA)",
        "Baldwin, Tammy (WI)",
        "Murphy, Christopher (CT)",
        "Kaine, Tim (VA)",
        "Hassan, Margaret Wood (NH)",
        "Hickenlooper, John W. (CO)",
        "Markey, Edward J. (MA)",
        "Kim, Andy (NJ)",
        "Blunt Rochester, Lisa (DE)",
        "Alsobrooks, Angela D. (MD)",
    ],
    "Homeland Security and Governmental Affairs": [
        "Paul, Rand (KY)",
        "Johnson, Ron (WI)",
        "Lankford, James (OK)",
        "Scott, Rick (FL)",
        "Hawley, Josh (MO)",
        "Moreno, Bernie (OH)",
        "Ernst, Joni (IA)",
        "Moody, Ashley (FL)",
        "Peters, Gary C. (MI)",
        "Hassan, Margaret Wood (NH)",
        "Blumenthal, Richard (CT)",
        "Fetterman, John (PA)",
        "Kim, Andy (NJ)",
        "Gallego, Ruben (AZ)",
        "Slotkin, Elissa (MI)",
    ],
    "Indian Affairs": [
        "Murkowski, Lisa (AK)",
        "Hoeven, John (ND)",
        "Daines, Steve (MT)",
        "Mullin, Markwayne (OK)",
        "Rounds, Mike (SD)",
        "Moran, Jerry (KS)",
        "Schatz, Brian (HI)",
        "Cantwell, Maria (WA)",
        "Cortez Masto, Catherine (NV)",
        "Smith, Tina (MN)",
        "Lujan, Ben Ray (NM)",
    ],
    "Rules and Administration": [
        "McConnell, Mitch (KY)",
        "Cruz, Ted (TX)",
        "Capito, Shelley Moore (WV)",
        "Wicker, Roger F. (MS)",
        "Fischer, Deb (NE)",
        "Hyde-Smith, Cindy (MS)",
        "Hagerty, Bill (TN)",
        "Britt, Katie Boyd (AL)",
        "Boozman, John (AR)",
        "Padilla, Alex (CA)",
        "Schumer, Charles E. (NY)",
        "Warner, Mark R. (VA)",
        "Klobuchar, Amy (MN)",
        "Merkley, Jeff (OR)",
        "Ossoff, Jon (GA)",
        "Bennet, Michael F. (CO)",
        "Welch, Peter (VT)",
    ],
    "Small Business and Entrepreneurship": [
        "Ernst, Joni (IA)",
        "Risch, James E. (ID)",
        "Paul, Rand (KY)",
        "Scott, Tim (SC)",
        "Young, Todd (IN)",
        "Hawley, Josh (MO)",
        "Budd, Ted (NC)",
        "Curtis, John R. (UT)",
        "Justice, James C. (WV)",
        "Husted, Jon (OH)",
        "Markey, Edward J. (MA)",
        "Cantwell, Maria (WA)",
        "Shaheen, Jeanne (NH)",
        "Booker, Cory A. (NJ)",
        "Coons, Christopher A. (DE)",
        "Hirono, Mazie K. (HI)",
        "Rosen, Jacky (NV)",
        "Hickenlooper, John W. (CO)",
        "Schiff, Adam B. (CA)",
    ],
    "Budget": [
        "Graham, Lindsey (SC)",
        "Grassley, Chuck (IA)",
        "Crapo, Mike (ID)",
        "Johnson, Ron (WI)",
        "Marshall, Roger (KS)",
        "Cornyn, John (TX)",
        "Lee, Mike (UT)",
        "Kennedy, John (LA)",
        "Ricketts, Pete (NE)",
        "Moreno, Bernie (OH)",
        "Scott, Rick (FL)",
        "Merkley, Jeff (OR)",
        "Murray, Patty (WA)",
        "Wyden, Ron (OR)",
        "Sanders, Bernard (VT)",
        "Whitehouse, Sheldon (RI)",
        "Warner, Mark R. (VA)",
        "Kaine, Tim (VA)",
        "Van Hollen, Chris (MD)",
        "Lujan, Ben Ray (NM)",
        "Padilla, Alex (CA)",
    ],
    "Judiciary": [
        "Grassley, Chuck (IA)",
        "Graham, Lindsey (SC)",
        "Cornyn, John (TX)",
        "Lee, Mike (UT)",
        "Cruz, Ted (TX)",
        "Hawley, Josh (MO)",
        "Tillis, Thom (NC)",
        "Kennedy, John (LA)",
        "Blackburn, Marsha (TN)",
        "Schmitt, Eric (MO)",
        "Britt, Katie Boyd (AL)",
        "Moody, Ashley (FL)",
        "Durbin, Richard J. (IL)",
        "Whitehouse, Sheldon (RI)",
        "Klobuchar, Amy (MN)",
        "Coons, Christopher A. (DE)",
        "Blumenthal, Richard (CT)",
        "Hirono, Mazie K. (HI)",
        "Booker, Cory A. (NJ)",
        "Padilla, Alex (CA)",
        "Welch, Peter (VT)",
        "Schiff, Adam B. (CA)",
    ],
    "Veterans' Affairs": [
        "Moran, Jerry (KS)",
        "Boozman, John (AR)",
        "Cassidy, Bill (LA)",
        "Tillis, Thom (NC)",
        "Sullivan, Dan (AK)",
        "Blackburn, Marsha (TN)",
        "Cramer, Kevin (ND)",
        "Tuberville, Tommy (AL)",
        "Banks, Jim (IN)",
        "Sheehy, Tim (MT)",
        "Blumenthal, Richard (CT)",
        "Murray, Patty (WA)",
        "Sanders, Bernard (VT)",
        "Hirono, Mazie K. (HI)",
        "Hassan, Margaret Wood (NH)",
        "King, Angus S. (ME)",
        "Duckworth, Tammy (IL)",
        "Gallego, Ruben (AZ)",
        "Slotkin, Elissa (MI)",
    ],
    "Printing": [
        "Fischer, Deb (NE)",
        "Hagerty, Bill (TN)",
        "Klobuchar, Amy (MN)",
        "Merkley, Jeff (OR)",
        "Padilla, Alex (CA)",
    ],
    "Taxation": [
        "Crapo, Mike (ID)",
        "Grassley, Chuck (IA)",
        "Cornyn, John (TX)",
        "Wyden, Ron (OR)",
        "Cantwell, Maria (WA)",
    ],
}
senate_committees_sectors = {
    "Agriculture, Nutrition, and Forestry": (
        gics_sectors["Agriculture"] if "Agriculture" in gics_sectors else "00"
    ),
    "Appropriations": gics_sectors["Financials"],
    "Armed Services": gics_sectors["Industrials"],
    "Banking, Housing, and Urban Affairs": gics_sectors["Financials"],
    "Commerce, Science, and Transportation": gics_sectors["Industrials"],
    "Energy and Natural Resources": gics_sectors["Energy"],
    "Environment and Public Works": gics_sectors["Utilities"],
    "Finance": gics_sectors["Financials"],
    "Foreign Relations": gics_sectors[None],
    "Health, Education, Labor, and Pensions": gics_sectors["Health Care"],
    "Homeland Security and Governmental Affairs": gics_sectors[None],
    "Indian Affairs": gics_sectors[None],
    "Rules and Administration": gics_sectors[None],
    "Small Business and Entrepreneurship": gics_sectors["Industrials"],
    "Budget": gics_sectors[None],
    "Judiciary": gics_sectors[None],
    "Veterans' Affairs": gics_sectors["Health Care"],
    "Printing": gics_sectors["Consumer Discretionary"],
    "Taxation": gics_sectors["Financials"],
}


def get_senate_committees():
    for committee in senate_committees.keys():
        members = senate_committees[committee]
        c_sector = Sector.objects.get(sector_code=senate_committees_sectors[committee])
        c = Committee(committee_name=committee, chamber="S", sector=c_sector)
        c.save()
        for member in members:
            # Last name
            lname = member.split(",")[0]
            # Two letter state code
            state = member.split("(")[-1][:-1]
            try:
                m = CongressMember.objects.get(last_name=lname, state=state)
                c.committee_members.add(m)
            except:
                print("Member not added", lname)

        c.save()


house_committees = {
    "Agriculture": [
        "Thompson, Glenn (PA)",
        "Craig, Angie (MN)",
        "Lucas, Frank (OK)",
        "Scott, Austin (GA)",
        "Crawford, Rick (AR)",
        "DesJarlais, Scott (TN)",
        "LaMalfa, Doug (CA)",
        "Rouzer, David (NC)",
        "Kelly, Trent (MS)",
        "Bacon, Don (NE)",
        "Bost, Mike (IL)",
        "Johnson, Dusty (SD)",
        "Baird, Jim (IN)",
        "Mann, Tracey (KS)",
        "Feenstra, Randy (IA)",
        "Miller, Mary (IL)",
        "Moore, Barry (AL)",
        "Cammack, Kat (FL)",
        "Finstad, Brad (MN)",
        "Rose, John (TN)",
        "Jackson, Ronny (TX)",
        "De La Cruz, Monica (TX)",
        "Nunn, Zach (IA)",
        "Van Orden, Derrick (WI)",
        "Newhouse, Dan (WA)",
        "Wied, Tony (WI)",
        "Bresnahan, Rob (PA)",
        "Messmer, Mark (IN)",
        "Harris, Mark (NC)",
        "Taylor, Dave (OH)",
        "Brown, Shontel (OH)",
        "Scott, David (GA)",
        "Costa, Jim (CA)",
        "McGovern, Jim (MA)",
        "Adams, Alma (NC)",
        "Hayes, Jahana (CT)",
        "Davids, Sharice (KS)",
        "Salinas, Andrea (OR)",
        "Davis, Don (NC)",
        "Tokuda, Jill (HI)",
        "Budzinski, Nikki (IL)",
    ],
    "Appropriations": [
        "Cole, Tom (OK)",
        "DeLauro, Rosa (CT)",
        "Rogers, Harold (KY)",
        "Aderholt, Robert (AL)",
        "Simpson, Michael (ID)",
        "Carter, John (TX)",
        "Calvert, Ken (CA)",
        "Diaz-Balart, Mario (FL)",
        "Womack, Steve (AR)",
        "Fleischmann, Charles (TN)",
        "Joyce, David (OH)",
        "Harris, Andy (MD)",
        "Amodei, Mark (NV)",
        "Valadao, David (CA)",
        "Newhouse, Dan (WA)",
        "Moolenaar, John (MI)",
        "Rutherford, John (FL)",
        "Cline, Ben (VA)",
        "Reschenthaler, Guy (PA)",
        "Hinson, Ashley (IA)",
        "Gonzales, Tony (TX)",
        "Letlow, Julia (LA)",
        "Cloud, Michael (TX)",
        "Guest, Michael (MS)",
        "Zinke, Ryan (MT)",
        "Clyde, Andrew (GA)",
        "Bice, Stephanie (OK)",
        "Franklin, Scott (FL)",
        "Ellzey, Jake (TX)",
        "Ciscomani, Juan (AZ)",
        "Edwards, Chuck (NC)",
        "Alford, Mark (MO)",
        "LaLota, Nick (NY)",
        "Strong, Dale (AL)",
        "Maloy, Celeste (UT)",
        "Moore, Riley (WV)",
        "Hoyer, Steny (MD)",
        "Kaptur, Marcy (OH)",
        "Clyburn, James (SC)",
        "Bishop, Sanford (GA)",
        "McCollum, Betty (MN)",
        "Wasserman Schultz, Debbie (FL)",
        "Cuellar, Henry (TX)",
        "Pingree, Chellie (ME)",
        "Quigley, Mike (IL)",
        "Meng, Grace (NY)",
        "Pocan, Mark (WI)",
        "Aguilar, Pete (CA)",
        "Frankel, Lois (FL)",
        "Watson Coleman, Bonnie (NJ)",
        "Torres, Norma (CA)",
        "Case, Ed (HI)",
        "Espaillat, Adriano (NY)",
        "Harder, Josh (CA)",
        "Underwood, Lauren (IL)",
        "Lee, Susie (NV)",
        "Morelle, Joseph (NY)",
        "Levin, Mike (CA)",
        "Dean, Madeleine (PA)",
        "Escobar, Veronica (TX)",
        "Mrvan, Frank (IN)",
        "Gluesenkamp Perez, Marie (WA)",
        "Ivey, Glenn (MD)",
    ],
    "Armed Services": [
        "Rogers, Mike (AL)",
        "Smith, Adam (WA)",
        "Wilson, Joe (SC)",
        "Turner, Michael R. (OH)",
        "Wittman, Robert J. (VA)",
        "Scott, Austin (GA)",
        "Graves, Sam (MO)",
        "Stefanik, Elise M. (NY)",
        "DesJarlais, Scott (TN)",
        "Kelly, Trent (MS)",
        "Bacon, Don (NE)",
        "Bergman, Jack (MI)",
        "Jackson, Ronny (TX)",
        "Fallon, Pat (TX)",
        "Gimenez, Carlos A. (FL)",
        "Mace, Nancy (SC)",
        "Finstad, Brad (MN)",
        "Luttrell, Morgan (TX)",
        "Kiggans, Jennifer A. (VA)",
        "Moylan, James C. (GU)",
        "Mills, Cory (FL)",
        "McCormick, Richard (GA)",
        "Gooden, Lance (TX)",
        "Higgins, Clay (LA)",
        "Van Orden, Derrick (WI)",
        "McGuire, John III (VA)",
        "Harrigan, Pat (NC)",
        "Messmer, Mark (IN)",
        "Schmidt, Derek (KS)",
        "Crank, Jeff (CO)",
        "Hamadeh, Abe (AZ)",
        "Courtney, Joe (CT)",
        "Garamendi, John (CA)",
        "Norcross, Donald (NJ)",
        "Moulton, Seth (MA)",
        "Carbajal, Salud O. (CA)",
        "Khanna, Ro (CA)",
        "Keating, William R. (MA)",
        "Houlahan, Chrissy (PA)",
        "Crow, Jason (CO)",
        "Sherrill, Mikie (NJ)",
        "Golden, Jared F. (ME)",
        "Jacobs, Sara (CA)",
        "Strickland, Marilyn (WA)",
        "Ryan, Patrick (NY)",
        "Vasquez, Gabe (NM)",
        "Deluzio, Christopher R. (PA)",
        "Tokuda, Jill N. (HI)",
        "Davis, Donald G. (NC)",
        "Cisneros, Gil (CA)",
        "Sorensen, Eric (IL)",
        "Goodlander, Maggie (NH)",
        "Elfreth, Sarah (MD)",
        "Whitesides, George (CA)",
        "Tran, Derek (CA)",
        "Vindman, Eugene (VA)",
        "Bell, Wesley (MO)",
    ],
    "Budget": [
        "Arrington, Jodey (TX)",
        "Boyle, Brendan (PA)",
        "Norman, Ralph (SC)",
        "McClintock, Tom (CA)",
        "Grothman, Glenn (WI)",
        "Smucker, Lloyd (PA)",
        "Carter, Buddy (GA)",
        "Cline, Ben (VA)",
        "Bergman, Jack (MI)",
        "Roy, Chip (TX)",
        "Stutzman, Marlin (IN)",
        "Moore, Blake (UT)",
        "Estes, Ron (KS)",
        "Brecheen, Josh (OK)",
        "Obernolte, Jay (CA)",
        "Carey, Mike (OH)",
        "Edwards, Chuck (NC)",
        "Clyde, Andrew (GA)",
        "Houchin, Erin (IN)",
        "McDowell, Addison (NC)",
        "Gill, Brandon (TX)",
        "Moore, Tim (NC)",
        "Doggett, Lloyd (TX)",
        "Scott, Robert (VA)",
        "Peters, Scott (CA)",
        "Panetta, Jimmy (CA)",
        "Watson Coleman, Bonnie (NJ)",
        "Plaskett, Stacey (VI)",
        "Escobar, Veronica (TX)",
        "Omar, Ilhan (MN)",
        "Balint, Becca (VT)",
        "Kaptur, Marcy (OH)",
        "Jayapal, Pramila (WA)",
        "Chu, Judy (CA)",
        "Tonko, Paul (NY)",
        "McGarvey, Morgan (KY)",
        "Amo, Gabe (RI)",
    ],
    "Education & Workforce": [
        "Walberg, Tim (MI)",
        "Wilson, Joe (SC)",
        "Foxx, Virginia (NC)",
        "Thompson, Glenn (PA)",
        "Grothman, Glenn (WI)",
        "Stefanik, Elise M. (NY)",
        "Allen, Rick W. (GA)",
        "Comer, James (KY)",
        "Owens, Burgess (UT)",
        "McClain, Lisa C. (MI)",
        "Miller, Mary E. (IL)",
        "Letlow, Julia (LA)",
        "Kiley, Kevin (CA)",
        "Houchin, Erin (IN)",
        "Rulli, Michael A. (OH)",
        "Moylan, James (GU)",
        "Onder, Robert F. (MO)",
        "Mackenzie, Ryan (PA)",
        "Baumgartner, Michael (WA)",
        "Harris, Mark (NC)",
        "Messmer, Mark B. (IN)",
        "Scott, Robert C. (VA)",
        "Grijalva, Raúl (AZ)",
        "Courtney, Joe (CT)",
        "Wilson, Frederica S. (FL)",
        "Bonamici, Suzanne (OR)",
        "Takano, Mark (CA)",
        "Adams, Alma S. (NC)",
        "DeSaulnier, Mark (CA)",
        "Norcross, Donald (NJ)",
        "McBath, Lucy (GA)",
        "Hayes, Jahana (CT)",
        "Omar, Ilhan (MN)",
        "Stevens, Haley M. (MI)",
        "Casar, Greg (TX)",
        "Lee, Summer L. (PA)",
        "Mannion, John W. (NY)",
    ],
    "Energy & Commerce": [
        "Guthrie, Brett (KY)",
        "Latta, Bob (OH)",
        "Griffith, Morgan (VA)",
        "Bilirakis, Gus (FL)",
        "Hudson, Richard (NC)",
        "Carter, Buddy (GA)",
        "Palmer, Gary (AL)",
        "Dunn, Neal M.D. (FL)",
        "Crenshaw, Dan (TX)",
        "Joyce, John (PA)",
        "Weber, Randy (TX)",
        "Allen, Rick (GA)",
        "Balderson, Troy (OH)",
        "Fulcher, Russ (ID)",
        "Pfluger, August (TX)",
        "Harshbarger, Diana (TN)",
        "Miller-Meeks, Mariannette (IA)",
        "Cammack, Kat (FL)",
        "Obernolte, Jay (CA)",
        "James, John (MI)",
        "Bentz, Cliff (OR)",
        "Houchin, Erin (IN)",
        "Fry, Russell (SC)",
        "Lee, Laurel (FL)",
        "Langworthy, Nick (NY)",
        "Kean, Tom (NJ)",
        "Rulli, Michael (OH)",
        "Evans, Gabe (CO)",
        "Goldman, Craig (TX)",
        "Fedorchak, Julie (ND)",
        "Pallone, Frank (NJ)",
        "DeGette, Diana (CO)",
        "Schakowsky, Jan (IL)",
        "Matsui, Doris (CA)",
        "Castor, Kathy (FL)",
        "Tonko, Paul (NY)",
        "Clarke, Yvette (NY)",
        "Ruiz, Raul (CA)",
        "Peters, Scott (CA)",
        "Dingell, Debbie (MI)",
        "Veasey, Marc (TX)",
        "Kelly, Robin (IL)",
        "Barragán, Nanette Diaz (CA)",
        "Soto, Darren (FL)",
        "Schrier, Kim (WA)",
        "Trahan, Lori (MA)",
        "Fletcher, Lizzie (TX)",
        "Ocasio-Cortez, Alexandria (NY)",
        "Auchincloss, Jake (MA)",
        "Carter, Troy (LA)",
        "Menendez, Rob (NJ)",
        "Mullin, Kevin (CA)",
        "Landsman, Greg (OH)",
        "McClellan, Jennifer (VA)",
    ],
    "Ethics": [
        "Guest, Michael (MS)",
        "Joyce, David P. (OH)",
        "Rutherford, John H. (FL)",
        "Garbarino, Andrew R. (NY)",
        "Fischbach, Michelle (MN)",
        "Wild, Susan (PA)",
        "Escobar, Veronica (TX)",
        "DeSaulnier, Mark (CA)",
        "Ross, Deborah K. (NC)",
        "Ivey, Glenn F. (MD)",
    ],
    "Financial Services": [
        "Hill, French (AR)",
        "Lucas, Frank D. (OK)",
        "Sessions, Pete (TX)",
        "Huizenga, Bill (MI)",
        "Wagner, Ann (MO)",
        "Barr, Andy (KY)",
        "Williams, Roger (TX)",
        "Emmer, Tom (MN)",
        "Loudermilk, Barry (GA)",
        "Davidson, Warren (OH)",
        "Rose, John (TN)",
        "Steil, Bryan (WI)",
        "Timmons, William (SC)",
        "Stutzman, Marlin (IN)",
        "Norman, Ralph (SC)",
        "Meuser, Dan (PA)",
        "Kim, Young (CA)",
        "Donalds, Byron (FL)",
        "Garbarino, Andrew (NY)",
        "Fitzgerald, Scott (WI)",
        "Flood, Mike (NE)",
        "Lawler, Mike (NY)",
        "De La Cruz, Monica (TX)",
        "Ogles, Andy (TN)",
        "Nunn, Zach (IA)",
        "McClain, Lisa (MI)",
        "Salazar, Maria (FL)",
        "Downing, Troy (MT)",
        "Haridopolos, Mike (FL)",
        "Moore, Tim (NC)",
        "Waters, Maxine (CA)",
        "Velázquez, Nydia M. (NY)",
        "Sherman, Brad (CA)",
        "Meeks, Gregory W. (NY)",
        "Scott, David (GA)",
        "Lynch, Stephen F. (MA)",
        "Green, Al (TX)",
        "Cleaver, Emanuel II (MO)",
        "Himes, Jim A. (CT)",
        "Foster, Bill (IL)",
        "Beatty, Joyce (OH)",
        "Vargas, Juan (CA)",
        "Gottheimer, Josh (NJ)",
        "Gonzalez, Vicente (TX)",
        "Casten, Sean (IL)",
        "Pressley, Ayanna (MA)",
        "Tlaib, Rashida (MI)",
        "Torres, Ritchie (NY)",
        "Garcia, Sylvia (TX)",
        "Williams, Nikema (GA)",
        "Pettersen, Brittany (CO)",
        "Fields, Cleo (LA)",
        "Bynum, Janelle (OR)",
        "Liccardo, Sam (CA)",
    ],
    "Foreign Affairs": [
        "Mast, Brian (FL)",
        "Meeks, Gregory (NY)",
        "McCaul, Michael (TX)",
        "Smith, Christopher (NJ)",
        "Issa, Darrell (CA)",
        "Wilson, Joe (SC)",
        "Perry, Scott (PA)",
        "Burchett, Tim (TN)",
        "Green, Mark (TN)",
        "Barr, Andy (KY)",
        "Jackson, Ronny (TX)",
        "Kim, Young (CA)",
        "Huizenga, Bill (MI)",
        "Radewagen, Amata (AS)",
        "Davidson, Warren (OH)",
        "Baird, Jim (IN)",
        "Kean Jr., Thomas (NJ)",
        "Lawler, Michael (NY)",
        "Mills, Cory (FL)",
        "Self, Keith (TX)",
        "Zinke, Ryan (MT)",
        "Moylan, James (GU)",
        "Salazar, Maria Elvira (FL)",
        "Baumgartner, Michael (WA)",
        "Shreve, Jefferson (IN)",
        "Mackenzie, Ryan (PA)",
        "Biggs, Sheri (SC)",
        "Luna, Anna Paulina (FL)",
        "Sherman, Brad (CA)",
        "Connolly, Gerald (VA)",
        "Keating, William (MA)",
        "Bera, Ami (CA)",
        "Castro, Joaquin (TX)",
        "Titus, Dina (NV)",
        "Lieu, Ted (CA)",
        "Jacobs, Sara (CA)",
        "Cherfilus-McCormick, Sheila (FL)",
        "Stanton, Greg (AZ)",
        "Moskowitz, Jared (FL)",
        "Jackson, Jonathan (IL)",
        "Kamlager-Dove, Sydney (CA)",
        "Costa, Jim (CA)",
        "Amo, Gabe (RI)",
        "Mfume, Kweisi (MD)",
        "Jayapal, Pramila (WA)",
        "Latimer, George (NY)",
        "Olszewski, Johnny (MD)",
        "Johnson, Julie (TX)",
        "McBride, Sarah (DE)",
    ],
    "Homeland Security": [
        "Green, Mark (TN)",
        "McCaul, Michael (TX)",
        "Higgins, Clay (LA)",
        "Guest, Michael (MS)",
        "Gimenez, Carlos (FL)",
        "Pfluger, August (TX)",
        "Garbarino, Andrew (NY)",
        "Greene, Marjorie Taylor (GA)",
        "Gonzales, Tony (TX)",
        "Luttrell, Morgan (TX)",
        "Strong, Dale (AL)",
        "Brecheen, Josh (OK)",
        "Crane, Eli (AZ)",
        "Ogles, Andy (TN)",
        "Biggs, Sheri (SC)",
        "Evans, Gabe (CO)",
        "Mackenzie, Ryan (PA)",
        "Knott, Brad (NC)",
        "Thompson, Bennie (MS)",
        "Swalwell, Eric (CA)",
        "Correa, Lou (CA)",
        "Thanedar, Shri (MI)",
        "Magaziner, Seth (RI)",
        "Goldman, Dan (NY)",
        "Ramirez, Delia (IL)",
        "Kennedy, Tim (NY)",
        "McIver, LaMonica (NJ)",
        "Johnson, Julie (TX)",
        "Hernández, Pablo José (PR)",
        "Pou, Nellie (NJ)",
    ],
    "House Administration": [
        "Steil, Bryan (WI)",
        "Morelle, Joe (NY)",
        "Lee, Laurel (FL)",
        "Loudermilk, Barry (GA)",
        "Griffith, Morgan (VA)",
        "Murphy, Greg (NC)",
        "Bice, Stephanie (OK)",
        "Carey, Mike (OH)",
        "Miller, Mary (IL)",
        "Sewell, Terri (AL)",
        "Torres, Norma (CA)",
        "Johnson, Julie (TX)",
    ],
    "Judiciary": [
        "Jordan, Jim (OH)",
        "Issa, Darrell (CA)",
        "Biggs, Andy (AZ)",
        "McClintock, Tom (CA)",
        "Tiffany, Thomas P. (WI)",
        "Massie, Thomas (KY)",
        "Roy, Chip (TX)",
        "Fitzgerald, Scott (WI)",
        "Cline, Ben (VA)",
        "Gooden, Lance (TX)",
        "Van Drew, Jefferson (NJ)",
        "Nehls, Troy (TX)",
        "Moore, Barry (AL)",
        "Kiley, Kevin (CA)",
        "Hageman, Harriet (WY)",
        "Lee, Laurel (FL)",
        "Hunt, Wesley (TX)",
        "Fry, Russell (SC)",
        "Grothman, Glenn (WI)",
        "Knott, Brad (NC)",
        "Harris, Mark (NC)",
        "Onder, Robert F. (MO)",
        "Schmidt, Derek (KS)",
        "Gill, Brandon (TX)",
        "Baumgartner, Michael (WA)",
        "Raskin, Jamie (MD)",
        "Nadler, Jerrold (NY)",
        "Lofgren, Zoe (CA)",
        "Cohen, Steve (TN)",
        "Johnson, Henry C. (GA)",
        "Swalwell, Eric (CA)",
        "Lieu, Ted (CA)",
        "Jayapal, Pramila (WA)",
        "Correa, J. Luis (CA)",
        "Scanlon, Mary Gay (PA)",
        "Neguse, Joe (CO)",
        "McBath, Lucy (GA)",
        "Ross, Deborah K. (NC)",
        "Balint, Becca (VT)",
        "García, Jesús G. (IL)",
        "Kamlager-Dove, Sydney (CA)",
        "Moskowitz, Jared (FL)",
        "Goldman, Daniel S. (NY)",
        "Crockett, Jasmine (TX)",
    ],
    "Natural Resources": [
        "Westerman, Bruce (AR)",
        "Wittman, Rob (VA)",
        "McClintock, Tom (CA)",
        "Gosar, Paul (AZ)",
        "Radewagen, Amata Coleman (AS)",
        "LaMalfa, Doug (CA)",
        "Webster, Daniel (FL)",
        "Fulcher, Russ (ID)",
        "Stauber, Pete (MN)",
        "Tiffany, Tom (WI)",
        "Boebert, Lauren (CO)",
        "Bentz, Cliff (OR)",
        "Kiggans, Jen (VA)",
        "Hunt, Wesley (TX)",
        "Collins, Mike (GA)",
        "Hageman, Harriet (WY)",
        "Amodei, Mark (NV)",
        "Walberg, Tim (MI)",
        "Ezell, Mike (MS)",
        "Maloy, Celeste (UT)",
        "McDowell, Addison (NC)",
        "Crank, Jeff (CO)",
        "Begich, Nick (AK)",
        "Hurd, Jeff (CO)",
        "Kennedy, Mike (UT)",
        "Huffman, Jared (CA)",
        "Grijalva, Raúl (AZ)",
        "Neguse, Joe (CO)",
        "Leger Fernández, Teresa (NM)",
        "Stansbury, Melanie (NM)",
        "Hoyle, Val (OR)",
        "Magaziner, Seth (RI)",
        "Velázquez, Nydia (NY)",
        "Dingell, Debbie (MI)",
        "Gray, Adam (CA)",
        "Elfreth, Sarah (MD)",
        "Dexter, Maxine (OR)",
        "Ansari, Yassamin (AZ)",
        "Brownley, Julia (CA)",
        "Soto, Darren (FL)",
        "Min, Dave (CA)",
        "Golden, Jared (ME)",
        "Hernández Rivera, Pablo José (PR)",
        "Randall, Emily (WA)",
        "Rivas, Luz (CA)",
    ],
    "Oversight & Government Reform": [
        "Comer, James (KY)",
        "Connolly, Gerald E. (VA)",
        "Jordan, Jim (OH)",
        "Turner, Michael (OH)",
        "Gosar, Paul (AZ)",
        "Foxx, Virginia (NC)",
        "Grothman, Glenn (WI)",
        "Cloud, Michael (TX)",
        "Palmer, Gary (AL)",
        "Higgins, Clay (LA)",
        "Sessions, Pete (TX)",
        "Biggs, Andy (AZ)",
        "Mace, Nancy (SC)",
        "Fallon, Pat (TX)",
        "Donalds, Byron (FL)",
        "Perry, Scott (PA)",
        "Timmons, William (SC)",
        "Burchett, Tim (TN)",
        "Greene, Marjorie Taylor (GA)",
        "Boebert, Lauren (CO)",
        "Luna, Anna Paulina (FL)",
        "Langworthy, Nick (NY)",
        "Burlison, Eric (MO)",
        "Crane, Eli (AZ)",
        "Jack, Brian (GA)",
        "McGuire, John (VA)",
        "Gill, Brandon (TX)",
        "Norton, Eleanor Holmes (DC)",
        "Lynch, Stephen (MA)",
        "Krishnamoorthi, Raja (IL)",
        "Khanna, Ro (CA)",
        "Mfume, Kweisi (MD)",
        "Brown, Shontel (OH)",
        "Stansbury, Melanie (NM)",
        "Garcia, Robert (CA)",
        "Frost, Maxwell (FL)",
        "Lee, Summer (PA)",
        "Casar, Greg (TX)",
        "Crockett, Jasmine (TX)",
        "Randall, Emily (WA)",
        "Subramanyam, Suhas (VA)",
        "Ansari, Yassamin (AZ)",
        "Bell, Wesley (MO)",
        "Simon, Lateefah (CA)",
        "Min, Dave (CA)",
        "Pressley, Ayanna (MA)",
        "Tlaib, Rashida (MI)",
    ],
    "Rules": [
        "Foxx, Virginia (NC)",
        "McGovern, Jim (MA)",
        "Fischbach, Michelle (MN)",
        "Scanlon, Mary Gay (PA)",
        "Norman, Ralph (SC)",
        "Neguse, Joe (CO)",
        "Roy, Chip (TX)",
        "Leger Fernández, Teresa (NM)",
        "Houchin, Erin (IN)",
        "Langworthy, Nicholas A. (NY)",
        "Scott, Austin (GA)",
        "Griffith, H. Morgan (VA)",
        "Jack, Brian (GA)",
    ],
    "Science, Space, and Technology": [
        "Babin, Brian (TX)",
        "Lofgren, Zoe (CA)",
        "Weber, Randy (TX)",
        "Baird, Jim (IN)",
        "Webster, Daniel (FL)",
        "Obernolte, Jay (CA)",
        "Fleischmann, Chuck (TN)",
        "Issa, Darrell (CA)",
        "Tenney, Claudia (NY)",
        "Franklin, Scott (FL)",
        "Miller, Max (OH)",
        "McCormick, Rich (GA)",
        "Collins, Mike (GA)",
        "Fong, Vince (CA)",
        "Rouzer, David (NC)",
        "Self, Keith (TX)",
        "Harrigan, Pat (NC)",
        "Biggs, Sheri (SC)",
        "Hurd, Jeff (CO)",
        "Haridopolos, Mike (FL)",
        "Kennedy, Mike (UT)",
        "Begich, Nick (AK)",
        "Bonamici, Suzanne (OR)",
        "Stevens, Haley (MI)",
        "Ross, Deborah (NC)",
        "Salinas, Andrea (OR)",
        "Foushee, Val (NC)",
        "Frost, Maxwell (FL)",
        "Sykes, Emilia (OH)",
        "Amo, Gabe (RI)",
        "Subramanyam, Suhas (VA)",
        "Rivas, Luz (CA)",
        "Turner, Sylvester (TX)",
        "McBride, Sarah (DE)",
        "Gillen, Laura (NY)",
        "Whitesides, George (CA)",
        "Friedman, Laura (CA)",
        "McClain-Delaney, April (MD)",
        "Riley, Josh (NY)",
    ],
    "Small Business": [
        "Williams, Roger (TX)",
        "Stauber, Pete (MN)",
        "Meuser, Dan (PA)",
        "Van Duyne, Beth (TX)",
        "Ellzey, Jake (TX)",
        "Alford, Mark (MO)",
        "LaLota, Nick (NY)",
        "Finstad, Brad (MN)",
        "Wied, Tony (WI)",
        "Bresnahan, Rob (PA)",
        "Jack, Brian (GA)",
        "Downing, Troy (MT)",
        "King-Hinds, Kimberlyn (MP)",
        "Schmidt, Derek (KS)",
        "Velázquez, Nydia (NY)",
        "McGarvey, Morgan (KY)",
        "Scholten, Hillary (MI)",
        "McIver, LaMonica (NJ)",
        "Cisneros, Gil (CA)",
        "Morrison, Kelly (MN)",
        "Latimer, George (NY)",
        "Tran, Derek (CA)",
        "Simon, Lateefah (CA)",
        "Olszewski, Johnny (MD)",
        "Conaway, Herb (NJ)",
        "Goodlander, Maggie (NH)",
        "Hagedorn, Jim (MN)",
    ],
    "Transportation and Infrastructure": [
        "Graves, Sam (MO)",
        "Crawford, Rick (AR)",
        "Webster, Daniel (FL)",
        "Massie, Thomas (KY)",
        "Perry, Scott (PA)",
        "Babin, Brian (TX)",
        "Rouzer, David (NC)",
        "Bost, Mike (IL)",
        "LaMalfa, Doug (CA)",
        "Westerman, Bruce (AR)",
        "Mast, Brian (FL)",
        "Stauber, Pete (MN)",
        "Burchett, Tim (TN)",
        "Johnson, Dusty (SD)",
        "Van Drew, Jeff (NJ)",
        "Nehls, Troy (TX)",
        "Mann, Tracey (KS)",
        "Owens, Burgess (UT)",
        "Burlison, Eric (MO)",
        "Collins, Mike (GA)",
        "Ezell, Mike (MS)",
        "Kiley, Kevin (CA)",
        "Fong, Vince (CA)",
        "Wied, Tony (WI)",
        "Barrett, Tom (MI)",
        "Begich, Nick (AK)",
        "Bresnahan, Rob (PA)",
        "Hurd, Jeff (CO)",
        "Shreve, Jefferson (IN)",
        "McDowell, Addison (NC)",
        "Taylor, Dave (OH)",
        "Knott, Brad (NC)",
        "King-Hinds, Kim (MP)",
        "Kennedy, Mike (UT)",
        "Onder, Bob (MO)",
        "Larsen, Rick (WA)",
        "Holmes Norton, Eleanor (DC)",
        "Nadler, Jerry (NY)",
        "Cohen, Steve (TN)",
        "Garamendi, John (CA)",
        "Johnson, Henry 'Hank' (GA)",
        "Carson, André (IN)",
        "Titus, Dina (NV)",
        "Huffman, Jared (CA)",
        "Brownley, Julia (CA)",
        "Wilson, Frederica (FL)",
        "DeSaulnier, Mark (CA)",
        "Carbajal, Salud (CA)",
        "Stanton, Greg (AZ)",
        "Davids, Sharice (KS)",
        "García, Jesús 'Chuy' (IL)",
        "Pappas, Chris (NH)",
        "Moulton, Seth (MA)",
        "Strickland, Marilyn (WA)",
        "Ryan, Pat (NY)",
        "Hoyle, Val (OR)",
        "Sykes, Emilia (OH)",
        "Scholten, Hillary (MI)",
        "Foushee, Valerie (NC)",
        "Deluzio, Chris (PA)",
        "Garcia, Robert (CA)",
        "Pou, Nellie (NJ)",
        "McDonald Rivet, Kristen (MI)",
        "Friedman, Laura (CA)",
        "Gillen, Laura (NY)",
        "Figures, Shomari (AL)",
    ],
    "Veterans' Affairs": [
        "Bost, Mike (IL)",
        "Radewagen, Amata Coleman (AS)",
        "Bergman, Jack (MI)",
        "Mace, Nancy (SC)",
        "Miller-Meeks, Mariannette (IA)",
        "Murphy, Greg (NC)",
        "Van Orden, Derrick (WI)",
        "Luttrell, Morgan (TX)",
        "Ciscomani, Juan (AZ)",
        "Self, Keith (TX)",
        "Kiggans, Jen (VA)",
        "Hamadeh, Abe (AZ)",
        "King-Hinds, Kimberlyn (MP)",
        "Barrett, Tom (MI)",
        "Takano, Mark (CA)",
        "Brownley, Julia (CA)",
        "Pappas, Chris (NH)",
        "Cherfilus-McCormick, Sheila (FL)",
        "McGarvey, Morgan (KY)",
        "Ramirez, Delia (IL)",
        "Budzinski, Nikki (IL)",
        "Kennedy, Tim (NY)",
        "Dexter, Maxine (OR)",
        "Conaway, Herb (NJ)",
        "Morrison, Kelly (MN)",
    ],
    "Ways & Means": [
        "Smith, Jason (MO)",
        "Neal, Richard (MA)",
        "Buchanan, Vern (FL)",
        "Smith, Adrian (NE)",
        "Kelly, Mike (PA)",
        "Schweikert, David (AZ)",
        "LaHood, Darin (IL)",
        "Arrington, Jodey (TX)",
        "Estes, Ron (KS)",
        "Smucker, Lloyd (PA)",
        "Hern, Kevin (OK)",
        "Miller, Carol (WV)",
        "Murphy, Greg (NC)",
        "Kustoff, David (TN)",
        "Fitzpatrick, Brian (PA)",
        "Steube, Greg (FL)",
        "Tenney, Claudia (NY)",
        "Fischbach, Michelle (MN)",
        "Moore, Blake (UT)",
        "Van Duyne, Beth (TX)",
        "Feenstra, Randy (IA)",
        "Malliotakis, Nicole (NY)",
        "Carey, Mike (OH)",
        "Yakym, Rudy (IN)",
        "Miller, Max (OH)",
        "Bean, Aaron (FL)",
        "Moran, Nathaniel (TX)",
        "Doggett, Lloyd (TX)",
        "Thompson, Mike (CA)",
        "Larson, John (CT)",
        "Davis, Danny (IL)",
        "Sanchez, Linda (CA)",
        "Sewell, Terri (AL)",
        "DelBene, Suzan (WA)",
        "Chu, Judy (CA)",
        "Moore, Gwen (WI)",
        "Boyle, Brendan (PA)",
        "Beyer, Don (VA)",
        "Evans, Dwight (PA)",
        "Schneider, Brad (IL)",
        "Panetta, Jimmy (CA)",
        "Gomez, Jimmy (CA)",
        "Horsford, Steven (NV)",
        "Plaskett, Stacey (VI)",
        "Suozzi, Thomas (NY)",
    ],
    "Select Committee on Intelligence": [
        "Crawford, Rick (AR)",
        "Himes, Jim (CT)",
        "Kelly, Trent (MS)",
        "Carson, Andre (IN)",
        "LaHood, Darin (IL)",
        "Castro, Joaquin (TX)",
        "Fitzpatrick, Brian (PA)",
        "Krishnamoorthi, Raja (IL)",
        "Scott, Austin (GA)",
        "Crow, Jason (CO)",
        "Hill, French (AR)",
        "Bera, Ami (CA)",
        "Crenshaw, Dan (TX)",
        "Plaskett, Stacey (VI)",
        "Perry, Scott (PA)",
        "Gottheimer, Josh (NJ)",
        "Jackson, Ronny (TX)",
        "Gomez, Jimmy (CA)",
        "Wagner, Ann (MO)",
        "Houlahan, Chrissy (PA)",
        "Cline, Ben (VA)",
        "Quigley, Mike (IL)",
        "Steube, Greg (FL)",
        "Tenney, Claudia (NY)",
        "Fallon, Pat (TX)",
    ],
    "Select Committee on the CCP": [
        "Moolenaar, John (MI)",
        "Krishnamoorthi, Raja (IL)",
        "Wittman, Robert (VA)",
        "Barr, Andy (KY)",
        "Newhouse, Dan (WA)",
        "LaHood, Darin (IL)",
        "Dunn, Neal (FL)",
        "Johnson, Dusty (SD)",
        "Hinson, Ashley (IA)",
        "Gimenez, Carlos (FL)",
        "Bilirakis, Gus (FL)",
        "Kim, Young (CA)",
        "Moran, Nathaniel (TX)",
        "Nunn, Zachary (IA)",
        "Castor, Kathy (FL)",
        "Carson, André (IN)",
        "Moulton, Seth (MA)",
        "Khanna, Ro (CA)",
        "Sherrill, Mikie (NJ)",
        "Stevens, Haley (MI)",
        "Torres, Ritchie (NY)",
        "Brown, Shontel (OH)",
        "Stanton, Greg (AZ)",
        "Tokuda, Jill (HI)",
    ],
    "Joint Economic Committee": [
        "Schweikert, David (AZ)",
        "Arrington, Jodey (TX)",
        "Estes, Ron (KS)",
        "Ferguson, Drew (GA)",
        "Smucker, Lloyd (PA)",
        "Malliotakis, Nicole (NY)",
        "Beyer, Don (VA)",
        "Trone, David (MD)",
        "Moore, Gwen (WI)",
        "Porter, Katie (CA)",
    ],
    "Joint Committee on Taxation": [
        "Smith, Jason (MO)",
        "Buchanan, Vern (FL)",
        "Smith, Adrian (NE)",
        "Neal, Richard (MA)",
        "Doggett, Lloyd (TX)",
    ],
}

house_committees_sectors = {
    "Agriculture": "Consumer Staples",
    "Appropriations": "Industrials",
    "Armed Services": "Industrials",
    "Budget": "Financials",
    "Education & Workforce": "Industrials",
    "Energy & Commerce": "Energy",
    "Ethics": "Industrials",
    "Financial Services": "Financials",
    "Foreign Affairs": "Consumer Discretionary",
    "Homeland Security": "Industrials",
    "House Administration": "Information Technology",
    "Judiciary": "Industrials",
    "Natural Resources": "Basic Materials",
    "Oversight & Government Reform": "Industrials",
    "Rules": "Industrials",
    "Science, Space, and Technology": "Technology",
    "Small Business": "Consumer Staples",
    "Transportation and Infrastructure": "Industrials",
    "Veterans' Affairs": "Industrials",
    "Ways & Means": "Financials",
    "Select Committee on Intelligence": "Technology",
    "Select Committee on the CCP": "Consumer Discretionary",
    "Joint Economic Committee": "Financials",
    "Joint Committee on Taxation": "Financials",
}


def get_house_committees():
    for committee in house_committees.keys():
        members = house_committees[committee]
        c_sector = Sector.objects.get(
            sector_code=gics_sectors[house_committees_sectors[committee]]
        )
        c = Committee(committee_name=committee, chamber="H", sector=c_sector)
        c.save()
        for member in members:
            # Last name
            lname = member.split(",")[0]
            name = member.split(",")
            fname = name[1].split("(")[0].strip()
            # Two letter state code
            state = member.split("(")[-1][:-1]
            try:
                m = CongressMember.objects.get(last_name=lname, chamber="H")
                c.committee_members.add(m)
            except:
                m = CongressMember.objects.get(
                    last_name=lname, state=state, chamber="H", first_name=fname
                )
                c.committee_members.add(m)

            finally:
                continue

        c.save()


if __name__ == "__main__":
    getSectors()
    getStocks()
    getMembers()
    get_house_committees()
    get_senate_committees()
