# Generated by Django 5.1.6 on 2025-09-02 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=255)),
                ('chamber', models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CongressMember',
            fields=[
                ('bio_guide_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=255)),
                ('chamber', models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], max_length=1)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('term', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.committee')),
                ('member', models.ForeignKey(db_column='bio_guide_id', on_delete=django.db.models.deletion.CASCADE, to='server.congressmember')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_members',
            field=models.ManyToManyField(through='server.CommitteeMembership', to='server.congressmember'),
        ),
        migrations.AddField(
            model_name='committee',
            name='sector',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='server.sector'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(default=models.CharField(max_length=9, primary_key=True, serialize=False), max_length=255)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('traded_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('price_at_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.ForeignKey(db_column='bio_guide_id', on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='server.congressmember')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.stock')),
            ],
        ),
    ]
